version: '3'
services: 
  db:
    image: postgres:11-alpine
    ports: 
      - 15432:5432
    volumes: 
      - ./postgres-tmp:/var/lib/postgresql/
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    security_opt:
      - seccomp=unconfined
